name: Deploy WebServer
on:
    push:
        branches:
            - main
        paths:
            - 'site/**'

jobs:
    deploy:
        name: Deploy WebServer
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: install-aws-cli
              uses: unfor19/install-aws-cli-action@v1
              with:
                  version: 2
                  verbose: false                     
                  arch: amd64                        

            - name: Copy files to S3
              if: steps.changes.outputs.changes == 'true'
              run: |
                aws s3 sync site s3://site-coodesh

            - name: Update Auto Scaling Group
              if: steps.changes.outputs.changes == 'true'
              run: | 
                aws autoscaling start-instance-refresh --auto-scaling-group-name asg-coodesh --strategy Rolling --preferences '{"MinHealthyPercentage": 100, "InstanceWarmup": 300}'